"""prospect experience education skills

Revision ID: bae09299c428
Revises: 11b939569fc0
Create Date: 2026-07-18 14:57:08.807251
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # JSONB(astext_type=Text()) renders reference it unqualified


revision: str = 'bae09299c428'
down_revision: Union[str, None] = '11b939569fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('education')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
